{
 "title": "Pizza Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP request by method / minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_count_total{method!=\"OPTIONS\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(__name__) (http_requests_count_total)",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "active_users_count_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Authentication attempts / minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "login_attempts_count_total{status=\"success\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "login_attempts_count_total{status=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pizza Orders",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "order_count_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage_percent{type=\"cpu\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "system_usage_percent{type=\"memory\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "order_bitcoin", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Service latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg(request_latency_milliseconds{type=\"avg\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "request_latency_milliseconds{type=\"avg\", endpoint_id=\"create_order\"}",
     "legendFormat": "Create Order"
    }
   ]
  }
 ]
}